name: Content Submission
description: Submit your own content to be included on this site
labels: enhancement
body:
- type: input
  id: url
  attributes:
    label: Content Url
    description: "Enter the full Url of the repository for your submission."
    placeholder: "https://github.com/user/repo"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: Provide a short description of your submission.
    placeholder: "Format: The problem it solves + who it solves it for + what's unique about the solution"
  validations:
    required: true
